name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Validate docker compose
        run: docker compose -f kafka-local/docker-compose.yml config